### ISSUE TITLE
Error when listing all airpick and lodge requests

### ISSUE THREAD

**Issue by mayinghan** [ufcsa/airpick#30]
Error when accessing http://airpick2.uflcsa.org/airpicklist and http://airpick2.uflcsa.org/lodgelist
```
Error: TypeError: Cannot read property 'firstName' of null
    at /Users/yinghanma/projects/ufcsa/airpick/server/api/pickreq-api.js:393:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 0)
```

**Comment by mayinghan** [comment]
Error due to db, code is fine
